version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    volumes:
      - ../src/db_data:/var/lib/postgresql/data
    networks:
      - backend_network
    expose:
      - 5432
    env_file:
      - ../src/.env

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    volumes:
      - type: bind
        source: ../src/
        target: /code/
    networks:
      - backend_network
      - nginx_network
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ../src/.env

  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ../src/volumes/static/
        target: /code/volumes/static
      - type: bind
        source: ../src/volumes/media/
        target: /code/volumes/media
    networks:
      - nginx_network
    depends_on:
      - db
      - backend

volumes:
  db_data:
    external: True


networks:
  nginx_network:
    external: True
  backend_network:
    external: True